name: flutter_real_estate
description: Flutter DTT real estate assessment project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.15
  provider: ^6.0.0
  http: ^1.1.0
  flutter_riverpod: ^2.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.0.1
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/dtt_banner/hdpi/
    - assets/images/dtt_banner/ldpi/
    - assets/images/dtt_banner/mdpi/
    - assets/images/dtt_banner/xhdpi/
    - assets/images/dtt_banner/xxhdpi/
    - assets/images/dtt_banner/xxxhdpi/

  fonts:
    - family: GothamSSm
      fonts:
        - asset: assets/fonts/Gotham SSm/GothamSSm-Black.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-BlackItalic.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Bold.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Book.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Light.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Medium.otf

  uses-material-design: true

flutter_native_splash:
  image: "assets/images/launcher_icon.png"
  color: "#E65541"
  android_12:
    image: "assets/images/launcher_icon.png"
    color: "#E65541"