name: flutter_real_estate
description: Flutter DTT real estate assessment project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: GothamSSm
      fonts:
        - asset: assets/fonts/Gotham SSm/GothamSSm-Black.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-BlackItalic.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Bold.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Book.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Light.otf
        - asset: assets/fonts/Gotham SSm/GothamSSm-Medium.otf


flutter_native_splash:
  color: "#E65541"
  android_12:
    color: "#E65541"